<a href="https://colab.research.google.com/github/Shivangi-18-7/my-first-repo/blob/main/assesment_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
with open("warehouse_data.txt","w")as file:
    file.write("120\n")
    file.write("85\n")
    file.write("200\n")
    file.write("95\n")
    file.write("150\n")

In [11]:
with open("warehouse_data.txt","r")as file:
  lines = file.readlines()
  values = [line.strip() for line in lines]

for value in values:
    print(value)

120
85
200
95
150


In [13]:
import numpy as np
array = np.array(values, dtype=int)

print("Array:", array)
print("Data type:", array.dtype)
print("Shape:", array.shape)
print("Size:", array.size)

print("Sum:", np.sum(array))
print("Maximum:", np.max(array))
print("Minimum:", np.min(array))

Array: [120  85 200  95 150]
Data type: int64
Shape: (5,)
Size: 5
Sum: 650
Maximum: 200
Minimum: 85


In [17]:
import numpy as np
values = ["120","85","200","error","150"]
arr = np.array(values, dtype=int)

print("Array:", array)
print("Data type:", array.dtype)
print("Shape:", array.shape)
print("Size:", array.size)

print("Sum:", np.sum(array))
print("Maximum:", np.max(array))
print("Minimum:", np.min(array))

ValueError: invalid literal for int() with base 10: 'error'

In [37]:
import numpy as np
np.random.seed(42)
num_students = 10
names_list = ("shiva","ayshu","kushi","kashvi","bilva")
names = np.random.choice(names_list, 10)
print(names)
ages =np.random.randint(15,19,10,)
print(ages)
maths =np.random.randint(40,101,10,)
print(maths)
science  =np.random.randint(40,101,10,)
print(science )
english=np.random.randint(40,101,10,)
print(english)
marks = np.column_stack((maths,science,english))
print(marks)
print("Shape:", marks.shape)
print("Dtype:", marks.dtype)

reshaped_marks = marks.reshape(2, 5, 3)
print("Reshaped array:\n", reshaped_marks)
slice_data = marks[:5, :2]
print("First 5 students (Maths & Science):\n", slice_data)


with open("student_records.txt","w")as file:
  file.write("names,ages,maths,science,english\n")
  for i in range(10):
        record = f"{names[i]},{ages[i]},{maths[i]},{science[i]},{english[i]}\n"
        file.write(record)
        print("Records written successfully!\n")

  with open("student_records.txt", "r") as file:
      lines = file.readlines()

['kashvi' 'bilva' 'kushi' 'bilva' 'bilva' 'ayshu' 'kushi' 'kushi' 'kushi'
 'bilva']
[18 18 18 17 16 15 16 18 18 16]
[ 77  41  99  60  72  51  97  61 100  83]
[64 88 66 98 81 67 99 55 54 86]
[90 83 94 91 96 42 76 90 46 60]
[[ 77  64  90]
 [ 41  88  83]
 [ 99  66  94]
 [ 60  98  91]
 [ 72  81  96]
 [ 51  67  42]
 [ 97  99  76]
 [ 61  55  90]
 [100  54  46]
 [ 83  86  60]]
Shape: (10, 3)
Dtype: int64
Reshaped array:
 [[[ 77  64  90]
  [ 41  88  83]
  [ 99  66  94]
  [ 60  98  91]
  [ 72  81  96]]

 [[ 51  67  42]
  [ 97  99  76]
  [ 61  55  90]
  [100  54  46]
  [ 83  86  60]]]
First 5 students (Maths & Science):
 [[77 64]
 [41 88]
 [99 66]
 [60 98]
 [72 81]]
Records written successfully!

Records written successfully!

Records written successfully!

Records written successfully!

Records written successfully!

Records written successfully!

Records written successfully!

Records written successfully!

Records written successfully!

Records written successfully!

